'use strict';
// One-time layout migration; retain the original inline icon library.
const fs = require('node:fs');
const old = fs.readFileSync('index.html', 'utf8');
const symbols = old.match(/<svg class="svg-library"[\s\S]*?<\/defs><\/svg>/)[0];
const html = `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#0c1410">
  <meta name="description" content="VESPER. Sobreviva às hordas, evolua e enfrente chefes em um jogo de ação totalmente offline.">
  <title>VESPER</title>
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'%3E%3Crect width='48' height='48' rx='12' fill='%23101512'/%3E%3Cpath d='M24 5 28 21 39 24 28 27 24 43 20 27 9 24 20 21Z' fill='%23d4a563'/%3E%3C/svg%3E">
  <style>
    :root{color-scheme:dark;--gold:#d9b373;--gold-light:#f5d79c;--ivory:#eee9da;--muted:#a0b1a0;--serif:Georgia,'Times New Roman',serif;--sans:'Segoe UI',Tahoma,Arial,sans-serif}
    *{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#0c1410}body{color:var(--ivory);font-family:var(--sans);overscroll-behavior:none}button{font:inherit;color:inherit;cursor:pointer;-webkit-tap-highlight-color:transparent;touch-action:manipulation}button:focus-visible{outline:2px solid var(--gold-light);outline-offset:4px}button:disabled{opacity:.3;cursor:default}button:hover:not(:disabled){filter:brightness(1.16)}button:active:not(:disabled){transform:translateY(1px)}[hidden]{display:none!important}svg{pointer-events:none}.icon{width:22px;height:22px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round;flex:none}.svg-library{position:absolute;width:0;height:0;overflow:hidden}
    .arena{position:fixed;inset:0;width:100%;height:100%;height:100dvh;isolation:isolate;overflow:hidden;touch-action:none;background:#121c18}#game-canvas{position:absolute;inset:0;width:100%;height:100%;display:block}.arena:after{content:'';position:absolute;inset:0;box-shadow:inset 0 0 100px #03090670;pointer-events:none;z-index:1}
    .game-controls{position:absolute;right:max(22px,env(safe-area-inset-right));top:max(22px,calc(env(safe-area-inset-top) + 16px));display:flex;gap:7px;z-index:12}.icon-btn{width:35px;height:35px;display:grid;place-items:center;background:#07130b94;border:1px solid #c9bf8f24;color:#c3ccb8;border-radius:5px;transition:background .15s}.icon-btn:hover{background:#304430b0}.icon-btn .icon{width:18px;height:18px}.arena[data-state="menu"] #pause-btn{display:none}.arena[data-state="upgrade"] .game-controls,.arena[data-state="gameover"] .game-controls{z-index:4}
    .hud{position:absolute;inset:0;z-index:3;pointer-events:none}.hud:before{content:'';position:absolute;left:0;right:0;top:0;height:105px;background:linear-gradient(#040c09b8,transparent)}.xp-track{position:absolute;top:env(safe-area-inset-top,0px);left:0;right:0;height:5px;background:#12372b9c}.xp-fill{width:0;height:100%;background:linear-gradient(90deg,#397b61,#a2e6b4);box-shadow:0 0 10px #72d99550}.health{position:absolute;left:max(24px,env(safe-area-inset-left));top:max(24px,calc(env(safe-area-inset-top) + 18px));width:180px}.health-label{display:flex;align-items:center;gap:8px;margin-bottom:7px}.health-label .icon{color:#d47c72;width:14px;height:14px}.health-label span{font-size:11px;font-weight:600;font-variant-numeric:tabular-nums;color:#e4d9cc;letter-spacing:.5px}.health-track{height:7px;background:#271c1be6;border:1px solid #b8736530;border-radius:2px;overflow:hidden}.health-fill{width:100%;height:100%;background:linear-gradient(90deg,#98453c,#e38c78);transition:width .12s}.xp-info{display:flex;gap:10px;align-items:center;margin-top:8px;font-size:9px;letter-spacing:.6px;font-variant-numeric:tabular-nums}.level{color:#cadac0;font-weight:700}.xp-text{color:#92b399}.survival{position:absolute;top:max(21px,calc(env(safe-area-inset-top) + 15px));left:50%;transform:translateX(-50%);text-align:center}.timer{font:27px/1.1 var(--serif);letter-spacing:2px;font-variant-numeric:tabular-nums;color:#f2e5cd;text-shadow:0 2px 10px #000}.kills{display:flex;justify-content:center;align-items:center;gap:6px;color:#d0b580;font-size:11px;margin-top:7px;font-variant-numeric:tabular-nums}.kills .icon{width:13px;height:13px}
    .boss-hud{position:absolute;top:max(98px,calc(env(safe-area-inset-top) + 92px));left:50%;transform:translateX(-50%);width:min(480px,calc(100% - 44px));max-height:28dvh;overflow:auto;scrollbar-width:thin;scrollbar-color:#ae8446 transparent;pointer-events:auto;padding:0 3px 4px}.boss-row{margin-bottom:12px;padding:10px 13px 12px;background:linear-gradient(90deg,#0c140ac2,#11180bd6,#0c140ac2);border-radius:3px;box-shadow:0 3px 18px #0002}.boss-heading{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:7px;color:var(--gold-light)}.boss-name{font-size:10px;font-weight:700;letter-spacing:1.3px;text-transform:uppercase;display:flex;align-items:center;gap:8px}.boss-name .icon{width:14px;height:14px}.boss-health{font-size:9px;color:#d2b681;font-variant-numeric:tabular-nums;white-space:nowrap}.boss-track{height:8px;background:#2f2515;border:1px solid #c6923c61;box-shadow:0 0 12px #d0a84410;border-radius:1px;overflow:hidden}.boss-fill{height:100%;width:100%;background:linear-gradient(90deg,#a57024,#e5b751,#f6dc91);transition:width .1s;box-shadow:0 0 12px #eac66c55}.boss-row.super-boss{background:linear-gradient(90deg,#22100bc9,#20110bdb,#22100bc9)}.super-boss .boss-name{color:#ffd995}.super-boss .boss-track{height:10px;border-color:#f0b653b0}
    .menu{position:absolute;inset:0;z-index:6;display:flex;justify-content:center;align-items:center;padding:35px 22px;background:radial-gradient(ellipse at center,#07120b85 5%,#06100935 65%,#050e0966);overflow:auto}.menu-content{text-align:center;width:min(100%,460px);margin:auto;padding:35px 35px 30px;background:radial-gradient(ellipse,#08100ce3 0%,#09110b96 55%,transparent 74%)}.menu-seal{width:59px;height:59px;color:var(--gold);filter:drop-shadow(0 0 18px #d4b06625)}h1{font:normal clamp(44px,6vw,72px)/1 var(--serif);letter-spacing:12px;margin:23px -12px 12px 0;color:#f5e4be;text-shadow:0 3px 25px #000}.subtitle{font-size:10px;letter-spacing:4px;color:#c4b58c;margin:0 0 43px}.primary{display:inline-flex;align-items:center;justify-content:center;gap:15px;min-width:230px;min-height:52px;padding:0 28px;border:1px solid #f4d49a;border-radius:3px;background:linear-gradient(120deg,#e6c285,#bd8f4d);color:#221d12;box-shadow:0 4px 30px #dbb36315;font-weight:750;font-size:12px;letter-spacing:1.7px}.primary .icon{width:15px;height:15px}.menu-controls{display:flex;justify-content:center;gap:20px;font-size:10px;color:#b0bfa8;margin-top:30px}.menu-controls span{display:flex;align-items:center;gap:6px}.menu-controls .icon{width:15px;height:15px;color:#bfa770}kbd{font:9px var(--sans);border:1px solid #bbc4a43b;border-radius:3px;padding:4px 6px;background:#1a281477;color:#ccd6ba}.best{font-size:9px;color:#91a486;margin-top:30px;letter-spacing:1.2px}.best strong{font-weight:500;color:#c0bc95;margin-left:5px;font-variant-numeric:tabular-nums}.mobile-copy{display:none}
    .overlay{position:absolute;inset:0;z-index:10;display:flex;align-items:center;justify-content:center;padding:36px 24px;background:#060e0bdb;backdrop-filter:blur(6px);overflow:auto;touch-action:pan-y}.dialog{width:min(100%,620px);margin:auto;text-align:center}.dialog-seal{width:36px;height:36px;color:var(--gold)}.dialog-kicker{font-size:10px;letter-spacing:2px;color:var(--gold);margin:15px 0 13px}.dialog h2{font:normal 36px/1.15 var(--serif);letter-spacing:1px;margin:0 0 25px;color:#ece2c8}.choices{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:0 0 21px}.upgrade{position:relative;min-height:215px;background:linear-gradient(145deg,#2a3929,#131f18);border:1px solid #b2b5785c;border-radius:4px;padding:24px;text-align:left;transition:background .15s,border-color .15s}.upgrade:hover{background:linear-gradient(145deg,#3d4f32,#213021);border-color:#e5c582}.upgrade-icon{display:grid;place-items:center;width:40px;height:40px;border:1px solid #c6b97e55;background:#b0a95c10;color:var(--gold);border-radius:4px;margin-bottom:18px}.upgrade kbd{position:absolute;right:20px;top:25px}.upgrade h3{font:21px var(--serif);color:#efe3c6;margin:0 0 10px}.upgrade p{font-size:12px;line-height:1.6;color:#b0c0a6;margin:0 0 14px}.upgrade-detail{font-size:10px;color:#d8b879;letter-spacing:.2px}.choice-tip{font-size:9px;color:#9eae8c;letter-spacing:1px;margin:0}.pause-dialog{width:min(100%,350px)}.pause-dialog h2{margin:22px 0 30px;font-size:36px;letter-spacing:5px}.secondary{border:0;background:none;padding:12px 18px;margin:14px auto 0;display:block;color:#bac7ad;font-size:10px;letter-spacing:1px}.gameover-dialog{width:min(100%,540px)}.gameover-dialog .dialog-seal{color:#ce8d71}.gameover-dialog h2{margin:19px 0 25px;font-size:36px}.final-stats{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid #bba97a29;border-bottom:1px solid #bba97a29;padding:24px 0;margin:0 0 30px;gap:14px}.final-stats strong{display:block;font:28px var(--serif);color:#ebd39f;font-variant-numeric:tabular-nums}.final-stats span{display:block;margin-top:9px;font-size:8px;letter-spacing:1px;color:#a1b294}.record-note{color:#c8ae70;font-size:10px;letter-spacing:.6px;margin:19px 0 0;min-height:15px}
    .joystick{display:none;position:absolute;left:max(27px,env(safe-area-inset-left));bottom:max(30px,env(safe-area-inset-bottom));width:112px;height:112px;z-index:4;border:1px solid #c6d7ad3d;border-radius:50%;background:#b1d08f0a;touch-action:none;pointer-events:auto}.joystick:before,.joystick:after{content:'';position:absolute;background:#e4e9ca13}.joystick:before{width:1px;height:80px;left:55px;top:15px}.joystick:after{height:1px;width:80px;top:55px;left:15px}.joystick-knob{position:absolute;width:44px;height:44px;left:33px;top:33px;background:#adca9759;border:1px solid #d6e3b576;border-radius:50%;box-shadow:0 2px 15px #0004}.toast{position:absolute;top:40%;left:50%;transform:translate(-50%,-50%);width:max-content;max-width:85%;padding:12px 25px;background:linear-gradient(90deg,transparent,#172214e8 15%,#172214e8 85%,transparent);color:#f5d396;z-index:5;pointer-events:none;text-align:center;font:18px var(--serif);letter-spacing:2px;text-shadow:0 2px 10px #000;transition:opacity .3s}.toast.faded{opacity:0}.arena:not([data-state="playing"]) .toast{visibility:hidden}.arena:not([data-state="playing"]) .joystick{visibility:hidden}
    @media(pointer:coarse){.joystick{display:block}.desktop-copy{display:none!important}.mobile-copy{display:inline!important}}
    @media(max-width:650px){.game-controls{right:max(13px,env(safe-area-inset-right));top:max(20px,calc(env(safe-area-inset-top) + 14px));gap:4px}.icon-btn{width:30px;height:31px}.icon-btn .icon{width:16px;height:16px}.health{left:max(15px,env(safe-area-inset-left));top:max(21px,calc(env(safe-area-inset-top) + 15px));width:124px}.health-label{gap:6px;margin-bottom:6px}.health-label span{font-size:10px}.health-label .icon{width:12px;height:12px}.health-track{height:6px}.xp-info{font-size:8px;gap:7px;margin-top:7px}.survival{top:max(21px,calc(env(safe-area-inset-top) + 15px))}.timer{font-size:23px;letter-spacing:1px}.kills{margin-top:6px;font-size:10px}.boss-hud{top:max(90px,calc(env(safe-area-inset-top) + 84px));width:calc(100% - 26px);max-height:29dvh}.boss-row{padding:9px 10px 10px;margin-bottom:8px}.boss-name{font-size:9px;letter-spacing:.8px;gap:6px}.boss-health{font-size:8px}.menu-content{padding:30px 0}.menu-seal{width:49px;height:49px}h1{font-size:49px;letter-spacing:9px;margin-right:-9px}.subtitle{font-size:8px;letter-spacing:3px;margin-bottom:34px}.primary{min-width:225px;font-size:11px;min-height:50px}.menu-controls{font-size:9px;gap:16px;margin-top:26px}.best{font-size:8px;margin-top:25px}.overlay{padding:28px 16px}.dialog h2{font-size:27px;letter-spacing:.5px;margin-bottom:22px}.dialog-kicker{font-size:9px;margin:13px 0}.choices{gap:11px}.upgrade{padding:19px 15px;min-height:226px}.upgrade-icon{width:35px;height:35px}.upgrade kbd{right:14px;top:22px}.upgrade h3{font-size:19px}.upgrade p{font-size:11px}.upgrade-detail{font-size:9px}.choice-tip{font-size:8px}.pause-dialog h2{font-size:31px;letter-spacing:4px}.gameover-dialog h2{font-size:31px}.final-stats{gap:6px;padding:22px 0}.final-stats strong{font-size:24px}.final-stats span{font-size:7px;letter-spacing:.6px}.joystick{display:block;width:104px;height:104px;left:23px;bottom:max(27px,env(safe-area-inset-bottom))}.joystick-knob{left:29px;top:29px}.joystick:before{left:51px;top:11px}.joystick:after{top:51px;left:11px}.desktop-copy{display:none!important}.mobile-copy{display:inline!important}.toast{font-size:16px}}
    @media(max-width:360px){.health{width:105px}.game-controls{gap:3px;right:10px}.icon-btn{width:27px;height:29px}.timer{font-size:20px}.survival{left:51%}.upgrade{padding:18px 12px}.upgrade h3{font-size:17px}.upgrade p{font-size:10px}.final-stats strong{font-size:21px}}
    @media(max-height:520px) and (orientation:landscape){.menu{padding:16px}.menu-content{padding:10px 0}.menu-seal{width:29px;height:29px}h1{font-size:43px;letter-spacing:9px;margin-top:12px;margin-bottom:7px}.subtitle{font-size:8px;margin-bottom:20px}.primary{min-height:44px}.menu-controls{margin-top:17px}.best{margin-top:14px}.overlay{padding:20px}.dialog-seal{display:none}.dialog h2{font-size:26px;margin-bottom:17px}.dialog-kicker{font-size:9px;margin:0 0 10px}.choices{margin-bottom:13px}.upgrade{min-height:156px;padding:15px 20px}.upgrade-icon{width:33px;height:33px;float:left;margin:0 13px 10px 0}.upgrade h3{font-size:19px;margin-top:5px}.upgrade p{clear:both;margin-bottom:7px;font-size:11px}.upgrade kbd{top:17px}.pause-dialog h2{margin:0 0 25px}.gameover-dialog h2{margin:0 0 18px}.final-stats{padding:17px 0;margin-bottom:21px}.boss-hud{top:83px;max-height:29dvh}.boss-row{padding:7px 12px;margin-bottom:7px}.boss-heading{margin-bottom:5px}.joystick{width:92px;height:92px;bottom:19px}.joystick-knob{left:23px;top:23px}.joystick:before{left:45px;top:6px}.joystick:after{top:45px;left:6px}}
    @media(prefers-reduced-motion:reduce){*{transition:none!important}}
  </style>
</head>
<body>
${symbols}
  <main class="arena" id="arena" aria-label="Arena de sobrevivência" data-state="menu">
    <canvas id="game-canvas" aria-label="Campo de batalha. Mova-se com WASD, setas ou controle de toque. Ataques automáticos.">Seu navegador precisa oferecer suporte ao Canvas para jogar.</canvas>
    <div class="game-controls" aria-label="Opções do jogo">
      <button class="icon-btn" id="sound-btn" title="Ativar som (M)" aria-label="Ativar som" aria-pressed="false"><svg class="icon"><use href="#i-muted"/></svg></button>
      <button class="icon-btn" id="fullscreen-btn" title="Tela cheia (F)" aria-label="Entrar em tela cheia"><svg class="icon"><use href="#i-expand"/></svg></button>
      <button class="icon-btn" id="pause-btn" title="Pausar (Esc ou P)" aria-label="Pausar jogo" disabled><svg class="icon"><use href="#i-pause"/></svg></button>
    </div>
    <div class="hud" id="hud" hidden>
      <div class="xp-track" role="progressbar" aria-label="Experiência" aria-valuemin="0" aria-valuemax="15" aria-valuenow="0" id="xp-bar"><div class="xp-fill" id="xp-fill"></div></div>
      <div class="health"><div class="health-label"><svg class="icon" aria-hidden="true"><use href="#i-heart"/></svg><span id="hp-text">100 / 100</span></div><div class="health-track" role="progressbar" aria-label="Vida" aria-valuemin="0" aria-valuemax="100" aria-valuenow="100" id="hp-bar"><div class="health-fill" id="hp-fill"></div></div><div class="xp-info"><span class="level" id="level">NV. 1</span><span class="xp-text" id="xp-text">0 / 15 XP</span></div></div>
      <div class="survival"><div class="timer" id="timer" aria-label="Tempo de sobrevivência">00:00</div><div class="kills" title="Abates"><svg class="icon" aria-hidden="true"><use href="#i-skull"/></svg><span id="kills" aria-label="Abates">0</span></div></div>
      <div class="boss-hud" id="boss-hud" aria-label="Chefes vivos" hidden><div id="boss-bars"></div></div>
      <div class="joystick" id="joystick" role="group" aria-label="Controle de movimento por toque"><div class="joystick-knob" id="joystick-knob"></div></div>
    </div>
    <div id="toast" class="toast faded" role="status" hidden></div>
    <section class="menu" id="menu" aria-label="Menu inicial">
      <div class="menu-content"><svg class="icon menu-seal" aria-hidden="true"><use href="#i-sigil"/></svg><h1>VESPER</h1><p class="subtitle">A ÚLTIMA VIGÍLIA</p><button class="primary" id="start-btn"><svg class="icon" aria-hidden="true"><use href="#i-play"/></svg> INICIAR JOGO</button><div class="menu-controls"><span class="desktop-copy"><kbd>WASD</kbd> / setas</span><span class="mobile-copy">Controle por toque</span><span><svg class="icon" aria-hidden="true"><use href="#i-blade"/></svg>Ataque automático</span></div><p class="best">RECORDE <strong id="best-time">—</strong></p></div>
    </section>
    <div class="overlay" id="upgrade-overlay" hidden><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="upgrade-title"><svg class="icon dialog-seal" aria-hidden="true"><use href="#i-sigil"/></svg><p class="dialog-kicker" id="upgrade-level">NÍVEL 2</p><h2 id="upgrade-title">Escolha um poder</h2><div class="choices" id="choices"></div><p class="choice-tip">PARTIDA PAUSADA<span class="desktop-copy"> · TECLAS 1 / 2</span></p></section></div>
    <div class="overlay" id="pause-overlay" hidden><section class="dialog pause-dialog" role="dialog" aria-modal="true" aria-labelledby="pause-title"><h2 id="pause-title">PAUSADO</h2><button class="primary" id="resume-btn"><svg class="icon" aria-hidden="true"><use href="#i-play"/></svg> CONTINUAR</button><button class="secondary" id="pause-restart-btn">RECOMEÇAR</button></section></div>
    <div class="overlay" id="gameover-overlay" hidden><section class="dialog gameover-dialog" role="dialog" aria-modal="true" aria-labelledby="gameover-title"><svg class="icon dialog-seal" aria-hidden="true"><use href="#i-skull"/></svg><h2 id="gameover-title">FIM DE JOGO</h2><div class="final-stats"><div><strong id="final-time">00:00</strong><span>TEMPO</span></div><div><strong id="final-kills">0</strong><span>ABATES</span></div><div><strong id="final-bosses">0</strong><span>CHEFES</span></div><div><strong id="final-level">1</strong><span>NÍVEL</span></div></div><button class="primary" id="restart-btn">TENTAR NOVAMENTE</button><p id="record-note" class="record-note"></p></section></div>
  </main>
  <script src="vesper-engine.js"></script>
  <script src="vesper-ui.js"></script>
</body>
</html>
`;
fs.writeFileSync('index.html', html, 'utf8');
console.log('Full-screen layout written. Run node build.cjs after source changes.');
